const users = [{
    _id: "123",
    username: "ir",
    password: "ir",
    firstName: "Tony",
    lastName: "Stark",
    email: "tony@stark.com",
    role: "FACULTY",
    dob: "1972-02-19"
}, {
    _id: "234",
    username: "dk",
    password: "dk",
    firstName: "Bruce",
    lastName: "Wayne",
    email: "bruce@wayne.com",
    dob: "1972-02-19",
    role: "STUDENT"
}, {
    _id: "345",
    username: "black_widow",
    password: "romanoff123",
    firstName: "Natasha",
    lastName: "Romanoff",
    email: "natasha@avengers.com",
    dob: "1984-11-22",
    role: "TA"
}, {
    _id: "456",
    username: "thor_odinson",
    password: "mjolnir123",
    firstName: "Thor",
    lastName: "Odinson",
    email: "thor@asgard.com",
    dob: "982-05-25",
    role: "STUDENT"
}, {
    _id: "567",
    username: "hulk_smash",
    password: "1",
    firstName: "Bruce",
    lastName: "Banner",
    email: "bruce@avengers.com",
    dob: "1969-12-18",
    role: "STUDENT"
}, {
    _id: "678",
    username: "rg",
    password: "rg",
    firstName: "Frodo",
    lastName: "Baggins",
    email: "frodo@shire.com",
    dob: "1368-09-22",
    role: "FACULTY"
}, {
    _id: "789",
    username: "strider",
    password: "aragorn123",
    firstName: "Aragorn",
    lastName: "Elessar",
    email: "aragorn@gondor.com",
    dob: "2931-03-01",
    role: "TA"
}, {
    _id: "890",
    username: "elf_archer",
    password: "legolas123",
    firstName: "Legolas",
    lastName: "Greenleaf",
    email: "legolas@mirkwood.com",
    dob: "2879-07-15",
    role: "STUDENT"
}, {
    _id: "901",
    username: "captain_america",
    password: "rogers123",
    firstName: "Steve",
    lastName: "Rogers",
    email: "steve@avengers.com",
    dob: "1918-07-04",
    role: "FACULTY"
}, {
    _id: "012",
    username: "scarlet_witch",
    password: "wanda123",
    firstName: "Wanda",
    lastName: "Maximoff",
    email: "wanda@avengers.com",
    dob: "1989-02-10",
    role: "STUDENT"
}, {
    _id: "1234",
    username: "spider_man",
    password: "parker123",
    firstName: "Peter",
    lastName: "Parker",
    email: "peter@avengers.com",
    dob: "2001-08-10",
    role: "STUDENT"
}, {
    _id: "2345",
    username: "doctor_strange",
    password: "strange123",
    firstName: "Stephen",
    lastName: "Strange",
    email: "stephen@avengers.com",
    dob: "1930-11-18",
    role: "FACULTY"
}]
export default users